services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: Fitness_Notebook
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456789"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./tp5
    container_name: backend-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_PASSWORD: 123456789
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: Fitness_Notebook
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork:
