# Etapa de construcción del frontend
FROM node:18-alpine as build-stage
WORKDIR /app
COPY ./tp5-frontend/package*.json ./
RUN npm install
COPY ./tp5-frontend/ ./
RUN npm run build

# Etapa final con Nginx
FROM nginx:alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
